# Generated by Django 3.2.4 on 2021-06-21 17:59

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('runningTimeInMinutes', models.IntegerField()),
                ('year', models.IntegerField()),
                ('rating', models.FloatField(null=True)),
                ('ratingCount', models.IntegerField()),
                ('topRank', models.IntegerField()),
                ('metaScore', models.IntegerField(blank=True, null=True)),
                ('userScore', models.FloatField(blank=True, null=True)),
                ('currentRank', models.IntegerField(blank=True, null=True)),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('tmdbRating', models.IntegerField(blank=True, null=True)),
                ('countries', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('cast', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('significants', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('overview', models.TextField(blank=True, null=True)),
                ('tagline', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('originalLanguage', models.CharField(blank=True, max_length=200, null=True)),
                ('streamingLinks', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='StreamingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img_url', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmes.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmes.user')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='streamings',
            field=models.ManyToManyField(to='filmes.StreamingService'),
        ),
        migrations.AddField(
            model_name='user',
            name='streamings',
            field=models.ManyToManyField(to='filmes.StreamingService'),
        ),
    ]
