# Generated by Django 3.2.4 on 2021-06-07 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('imdb_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('release_year', models.IntegerField()),
                ('plot', models.TextField()),
                ('director', models.CharField(max_length=200)),
                ('rotten_rating', models.IntegerField()),
                ('metacritic_rating', models.IntegerField()),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmes.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmes.user')),
            ],
        ),
    ]
