# Generated by Django 3.2.4 on 2021-06-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0002_auto_20210621_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='streamings',
            field=models.ManyToManyField(blank=True, to='filmes.StreamingService'),
        ),
        migrations.AlterField(
            model_name='user',
            name='streamings',
            field=models.ManyToManyField(blank=True, to='filmes.StreamingService'),
        ),
    ]
