# Generated by Django 3.2.5 on 2021-07-17 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0004_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmes.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmes.user')),
            ],
        ),
    ]
