# Generated by Django 3.2.5 on 2021-07-18 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0006_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
