# Generated by Django 3.2.5 on 2021-07-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0007_remove_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
