name: Deploy backend
on:
  push:
    branches:
      - main
    paths:
      - backend_filmes/**
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: backend_filmes

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.6

      - name: Install dependencies
        run: poetry install

      - name: Lint with flake8
        run: poetry run flake8 --max-line-length 88 --exclude migrations

      - name: Test
        run: potry run pytest || true

      - name: Generate requirements.txt
        run: poetry export -f requirements.txt > requirements.txt

      - name: Create requirements.txt artifact
        uses: actions/upload-artifact@v2
        with:
          name: requirements.txt
          path: backend_filmes/requirements.txt
          retention-days: 1
          if-no-files-found: error

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download requirements.txt artifact
        uses: actions/download-artifact@v2
        with:
          name: requirements.txt
          path: backend_filmes

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: backend_filmes
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/labsoft2-filmes-backend:latest
          file: backend_filmes/Dockerfile
